config/routes.rb
Rails.application.routes.draw do
  root 'artists#index'
  resources :artists
  resources :songs

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :songs, dependent: :destroy
  mount_uploader :image, ImageUploader
end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :artist
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
  end

  def show
    @artist = Artist.find(params[:id])
  end

  def new
    @artist = Artist.new
  end

  def create
    if @artist = Artist.create(artist_params)
      redirect_to @artist
    else
      render :new
    end
  end

  def edit
    @artist = Artist.find(params[:id])
  end

  def update
    @artist = Artist.find(params[:id])
    if @artist.update(artist_params)
      redirect_to @artist
    else
      render :edit
    end
  end

  def destroy
    @artist = Artist.find (params[:id])
    if @artist.destroy
      redirect_to root_path
    else
      redirect_to @artist
    end
  end

  private

  def artist_params
    params.require(:artist).permit(:name, :biography, :genre, :image)
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
    @songs = Song.all
  end

  def show
    @song = Song.find(params[:id])
  end

  def new
    @song = Song.new
  end

  def create
    if @song = Song.create(song_params)
      redirect_to @song
    else
      render :new
    end
  end

  def edit
    @song = Song.find(params[:id])
  end

  def update
    @song = Song.find(params[:id])
    if @song.update(song_params)
      redirect_to @song
    else
      render :edit
    end
  end

  def destroy
    @song = Song.find(params[:id])
    if @song.destroy
      redirect_to songs_path
    else
      redirect_to @song
    end
  end

  private

  def song_params
    params.require(:song).permit(:title, :artist_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_form.html.erb
<%= form_for(@artist) do |f| %>

  <p><%= f.label :name %></p>
  <p><%= f.text_field :name %></p>

  <p><%= f.label :biography %></p>
  <p><%= f.text_field :biography %></p>

  <p><%= f.label :genre %></p>
  <p><%= f.text_field :genre %></p>

  <p><%= f.label :image %></p>
  <p><%= f.file_field :image %></p>

  <p><%= f.submit "Save" %></p>

<% end %>

app/views/artists/edit.html.erb
<h1>Edit Artist</h1>

<%= render "form" %>
<%= link_to "Back", @artist %>

app/views/artists/index.html.erb
<h1>Artists
<%= link_to "Add artist", new_artist_path, class: "btn btn-default" %></h1>

<% @artists.each do |artist| %>
  <h2><%= image_tag artist.image.thumb %>
  <%= link_to artist.name, artist %></h2>
<% end %>

app/views/artists/show.html.erb
<h1><%= @artist.name %>
<%= link_to "Edit artist", edit_artist_path, class: "btn btn-default" %>
<%= link_to "Delete artist", artist_path, class: "btn btn-default", method: :delete %></h1>


<p><%= image_tag @artist.image.large %></p>
<p><%= @artist.biography %></p>
<p>Genre: <%= @artist.genre %></p>

<h2>Songs</h2>
<% @artist.songs.each do |song| %>
  <p><%= link_to song.title, song %></p>
<% end %>

<%= link_to "Add song", new_song_path, class: "btn btn-default" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Music Database</title>

    <!-- Bootstrap -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>

    <%= render 'shared/navigation' %>

    <div class="container">
      <%= yield %>
    </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>
  </body>
</html>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" ><%= link_to "Music Database", root_path, :class => "navbar-brand" %></a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Artists", root_path %></li>
        <li><%= link_to "Songs", songs_path %></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/songs/_form.html.erb
<%= form_for(@song) do |f| %>

  <p><%= collection_select(:song, :artist_id, Artist.all, :id, :name) %></p>

  <p><%= f.label :title %></p>
  <p><%= f.text_field :title %></p>

  <p><%= f.submit "Save" %></p>

<% end %>

app/views/songs/edit.html.erb
<h1>Edit Song</h1>

<%= render "form" %>
<%= link_to "Back", @song %>

app/views/songs/index.html.erb
<h1>Songs
<%= link_to "Add song", new_song_path, class: "btn btn-default" %></h1>

<% @songs.each do |song| %>
  <p><%= link_to song.title, song %></p>
<% end %>

app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render "form" %>
<%= link_to "Back", root_path %>

app/views/songs/show.html.erb
  <h1><%= @song.title %>
  <%= link_to "Edit song", edit_song_path, class: "btn btn-default" %>
  <%= link_to "Delete song", song_path, class: "btn btn-default", method: :delete %></h1>


  <p><%= link_to @song.artist.name, @song.artist if @song.artist %></p>